//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class App
    {
        public App()
        {
            this.Comments = new HashSet<Comment>();
            this.Images = new HashSet<Image>();
            this.SectorOfferings = new HashSet<SectorOffering>();
            this.Technologies = new HashSet<Technology>();
            this.UserTypes = new HashSet<UserType>();
        }
    
        public string name { get; set; }
        public string desc { get; set; }
        public string impact { get; set; }
        public string issue { get; set; }
        public string idea { get; set; }
        public Nullable<System.DateTime> submittedDate { get; set; }
        public int appId { get; set; }
        public Nullable<int> submittedBy { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Image> Images { get; set; }
        public virtual ICollection<SectorOffering> SectorOfferings { get; set; }
        public virtual ICollection<Technology> Technologies { get; set; }
        public virtual ICollection<UserType> UserTypes { get; set; }
    }
}
