//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ISTOREEntities3 : DbContext
    {
        public ISTOREEntities3()
            : base("name=ISTOREEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ViewAppDetail> ViewAppDetails { get; set; }
        public DbSet<ViewAppDetails2> ViewAppDetails2 { get; set; }
        public DbSet<ViewApp> ViewApps { get; set; }
        public DbSet<ViewSector> ViewSectors { get; set; }
        public DbSet<ViewTech> ViewTeches { get; set; }
    }
}
