//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public byte[] pict { get; set; }
        public int sequence { get; set; }
        public int type { get; set; }
        public int imageId { get; set; }
        public int appId { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    
        public virtual App App { get; set; }
    }
}
