//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ISTOREEntities1 : DbContext
    {
        public ISTOREEntities1()
            : base("name=ISTOREEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<App> Apps { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Image> Images { get; set; }
        public DbSet<SectorOffering> SectorOfferings { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Technology> Technologies { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
    
        public virtual ObjectResult<GetAppDetails_Result> GetAppDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAppDetails_Result>("GetAppDetails");
        }
    }
}
