//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        public UserType()
        {
            this.Apps = new HashSet<App>();
        }
    
        public string name { get; set; }
        public int userTypeId { get; set; }
    
        public virtual ICollection<App> Apps { get; set; }
    }
}
