//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewApp
    {
        public int appId { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public string impact { get; set; }
        public string issue { get; set; }
        public string idea { get; set; }
        public Nullable<System.DateTime> submittedDate { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public byte[] pict { get; set; }
    }
}
