//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAppDetails2
    {
        public string comment { get; set; }
        public int commentId { get; set; }
        public int appId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public int rating { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
